// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectFinalEMDAAdvanced.Data;

namespace ProjectFinalEMDAAdvanced.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ProjectFinalEMDAAdvanced.Models.Reasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Reason");

                    b.Property<int>("ReasonCount");

                    b.HasKey("Id");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("ProjectFinalEMDAAdvanced.Models.SignOuts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Day");

                    b.Property<string>("HoursIn");

                    b.Property<int?>("ReasonId");

                    b.Property<int?>("StaffId");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.HasIndex("ReasonId");

                    b.HasIndex("StaffId");

                    b.ToTable("SignOuts");
                });

            modelBuilder.Entity("ProjectFinalEMDAAdvanced.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<bool>("In");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("TimeIn");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("ProjectFinalEMDAAdvanced.Models.SignOuts", b =>
                {
                    b.HasOne("ProjectFinalEMDAAdvanced.Models.Reasons", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId");

                    b.HasOne("ProjectFinalEMDAAdvanced.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");
                });
#pragma warning restore 612, 618
        }
    }
}
